language: node_js
sudo: false

node_js:
  - 'node'


before_script:
  - export PATH=/home/travis/node_modules/.bin:$PATH

install:
  - npm install markdown-pdf

script:
  - make

deploy:
  provider: releases
  file:
    - "protocols.zip"
    - "protocols.tar.gz"
    - "protocols/full-protocols.pdf"
    - "mass_spec/workflow.pdf"
  skip_cleanup: true
  on:
    repo: white-lab/protocols
    tags: true
